# Configure your application
shared: &shared
  # Configure your app's name
  app_name: Fugacious

  # This establishes the maximum number of hours that a message can be active.
  max_retention_hours: 720 # 30 days

  # Your secret key is used for verifying the integrity of signed cookies.
  # If you change this key, all old signed cookies will become invalid!
  # Make sure the secret is at least 30 characters and all random,
  # no regular words or you'll be exposed to dictionary attacks.
  # You can use `rake secret` to generate a secure secret key.
  secret_key_base: 9d1035ac2a2452075aabf407d7ec0ddd3d356f23d411e9b95cea64dde846ead04591a2c94e2418a94984a469104d1752d734286435ea32801cd7c120a5aea6e0

development:
  <<: *shared

test:
  <<: *shared

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  app_name: <%= ENV['APP_NAME'] %>
  max_retention_hours: <%= ENV['MAX_RETENTION_HOURS'] %>
  secret_key_base: <%= ENV['SECRET_KEY_BASE'] %>
